<style type="text/css">

/*
General Styles 
*/

* { font-family:"lucida grande",tahoma,verdana,arial,sans-serif; font-size:14px; color: #333333; /* don't use just black, it won't look good */ }

.fanmap_list table { margin-left:20px; margin-top:17px; width:370px; text-align:center; }
.fanmap_list th.name_heading { color:#333333; font-size:11px; font-weight:bold; }
.fanmap_list table th { border-color:#C7CFE0; border-bottom:1px solid #E2E6EF; margin:0; padding:3px; color:#777777; font-size:9px; }
.fanmap_list td { border-bottom:1px solid #E2E6EF; margin:0; padding:3px; color:#555555; font-size:11px; }
.fanmap_list table .even_colomn { background:#F8F8F8 none repeat scroll 0 0; }
.fanmap_list td.action_text { width:230px; }

/*
Tab Styles, fit fo look like an application tab set
*/

/* BEGIN TAB APPEARANCE */
.clearfix:after { content: "."; display: block; clear: both; visibility: hidden; line-height: 0; height: 0; }
.clearfix { display: inline-block; }
html[xmlns] .clearfix { display: block; }
* html .clearfix { height: 1%; }
.fb-tabs { padding: 0px; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #898989; width: 100%; }
.fb-tabs .left_tabs { float: left; padding-left: 10px; }
.fb-tabs .right_tabs { float: right; padding-right: 10px; }
.fb-tabitems { display: inline; list-style: none; margin: 0; padding: 0; text-align: center; }
.fb-tabitems li { list-style:none; float:left; background: #f1f1f1 url(http://www.facebook.com/images/components/toggle_fanmap_tab_gloss.gif) top left repeat-x; margin-top: 0; margin-right: 0px; margin-bottom: -1px; margin-left: 0px; padding-top: 2px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; }
.fb-tabitems li a { border: 1px solid #898989; display:block; color: #333; font-weight: bold; padding-top: 2px; padding-right: 8px; padding-bottom: 2px; padding-left: 9px; }
.fb-tabitems li a small { font-size: 11px; font-weight: normal; }
.fb-tabitems li a:focus { outline: 0px; }
.fb-tabitems li.first a { border:1px solid #898989; }
.fb-tabitems li a.selected { background: #6d84b4; border: 1px solid #3b5998; border-left: 1px solid #5973a9; border-right: 1px solid #5973a9; color: #fff; margin-left: -1px; }
.fb-tabitems li.last a.selected { margin-left:-1px; border-left:1px solid #5973a9; border-right:1px solid #36538f; }
.fb-tabitems li.first a.selected { margin: 0; border-left: 1px solid #36538f; border-right: 1px solid #5973a9; }
.fb-tabitems li.first.last a.selected { border: 1px solid #36538f; }
.fb-tabitems li a.selected:hover { text-decoration: none; }
/* END TAB APPEARANCE */

/* BEGIN CONTENT APPEARANCE */
.content { border-width: 1px; border-style: solid; border-color: #898989; padding-left: 8px; padding-top:3px; padding-right: 8px; padding-bottom:3px; }
.content #tabOne {
   /* Put CSS code here to alter the look and feel of the displayed Tab One content */
}
.content #tabTwo {
   /* Put CSS code here to alter the look and feel of the displayed Tab Two content */
}
.content #tabThree {
   /* Put CSS code here to alter the look and feel of the displayed Tab Three content */
}
.content #tabFour {
   /* Put CSS code here to alter the look and feel of the displayed Tab Four content */
}
.content #tabFive {
   /* Put CSS code here to alter the look and feel of the displayed Tab Five content */
}
/* END CONTENT APPEARANCE */
</style>

